# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: dukus.digiCamControl
PackageVersion: 2.1.6.0
PackageLocale: en-US
Publisher: dukus
PublisherUrl: https://digicamcontrol.com/
PublisherSupportUrl: https://sourceforge.net/projects/digicamcontrol/support
PackageName: digiCamControl
PackageUrl: https://digicamcontrol.com/download
License: MIT License
Copyright: Duka Istvan
ShortDescription: digiCamControl
ManifestType: defaultLocale
ManifestVersion: 1.4.0
